![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [3]:
import numpy as np

np.__version__

'1.24.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [4]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [5]:
my_arra2 = np.ones(9).reshape(3,3)
my_array2_bool =np.array(my_arra2 == 1)
print(my_array2_bool)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [24]:
np.full([3,3], True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [6]:
my_array_imparbool = np.array(my_array % 2 != 0)
my_array_impar = my_array[my_array_imparbool]
print(my_array_impar)

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [25]:
my_array3 = my_array.copy()

mask = my_array % 2 != 0

my_array3[mask] = -1
print(my_array3)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [8]:
my_array4 = np.where(my_array % 2 != 0, -1, my_array)
my_array4

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [9]:
my_array.reshape(2, int(my_array.size/2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate([a,b])
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [11]:
d = np.concatenate([a, b,], axis=1)
d

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [13]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [14]:
my_array = np.arange(10)
print(my_array)
my_arra2 = my_array * 10
print(my_arra2)
print(my_array[0])
print(my_array[-1])
print(my_array[1:8])

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [15]:
my_matrix = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [16]:
secuence = np.arange(start=1, stop=50, step=3)
secuence

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [17]:
secuence2 = np.arange(4, 1.26, -0.25)
secuence2

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ])

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [18]:
from skimage.io import imread
imagen = imread("./img/numpy.png")
imagen

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       ...,

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [19]:
my_array3 = np.arange(4).reshape(4,1)
print(my_array3)
my_array3.reshape(2,2)

[[0]
 [1]
 [2]
 [3]]


array([[0, 1],
       [2, 3]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [20]:
rand_matrix = np.random.rand(4, 5, 3)
rand_matrix

array([[[0.54733119, 0.70463478, 0.1096826 ],
        [0.00431464, 0.79925392, 0.08991078],
        [0.9293567 , 0.520074  , 0.98068283],
        [0.45899018, 0.78381597, 0.23677632],
        [0.55699078, 0.52742403, 0.72972617]],

       [[0.79156543, 0.24609883, 0.43096667],
        [0.11370362, 0.00569045, 0.35327109],
        [0.36634616, 0.08111421, 0.66585619],
        [0.79773462, 0.9920422 , 0.21388925],
        [0.4783525 , 0.45111392, 0.78379803]],

       [[0.29787147, 0.30819567, 0.21205163],
        [0.24112153, 0.29125597, 0.71136442],
        [0.20779469, 0.54887673, 0.81658219],
        [0.45308471, 0.7451288 , 0.70277582],
        [0.81189204, 0.90693436, 0.35100741]],

       [[0.58667752, 0.30260065, 0.62322644],
        [0.76941199, 0.05465747, 0.46773158],
        [0.83486462, 0.33729171, 0.7820362 ],
        [0.06718314, 0.36621196, 0.580031  ],
        [0.41528162, 0.12093049, 0.51770378]]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [21]:
my_matrix2 = np.arange(10).reshape(10, 1)
my_matrix2 = np.where(my_matrix2 < 0, True, False)
print(my_matrix2)
my_matrix2.reshape(2,5)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]


array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [22]:
x =np.random.randint(10, 20, size = (5,2,6))
print(x.size)
print(x.ndim)
print(x.shape)


60
3
(5, 2, 6)
